// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

type AppState struct {
	ID        int64
	LastPoll  int64
	LastAdded int64
}

type Collection struct {
	ID          string
	Name        string
	Description string
	SourceIds   string
	AddedAt     int64
}

type Config struct {
	ID         string
	Name       string
	ConfigJson string
	AddedAt    int64
}

type Item struct {
	ID        string
	SourceID  string
	Label     string
	ImageKey  string
	Url       string
	Sample    string
	Title     string
	Status    string
	Gone      int64
	AddedAt   int64
	LastSeen  int64
	DecidedAt int64
}

type Source struct {
	ID          string
	Name        string
	Description string
	Url         string
	ConfigFile  string
	ConfigJson  string
	AddedAt     int64
	LastPoll    int64
	LastAdded   int64
	LastError   string
	ConfigID    string
}
