// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package mysql

import (
	"context"
)

const countBySourceStatusGone = `-- name: CountBySourceStatusGone :many
SELECT source_id, status, gone, COUNT(*) AS n FROM items GROUP BY source_id, status, gone
`

type CountBySourceStatusGoneRow struct {
	SourceID string
	Status   string
	Gone     int64
	N        int64
}

func (q *Queries) CountBySourceStatusGone(ctx context.Context) ([]CountBySourceStatusGoneRow, error) {
	rows, err := q.db.QueryContext(ctx, countBySourceStatusGone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountBySourceStatusGoneRow
	for rows.Next() {
		var i CountBySourceStatusGoneRow
		if err := rows.Scan(
			&i.SourceID,
			&i.Status,
			&i.Gone,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countByStatusGone = `-- name: CountByStatusGone :many
SELECT status, gone, COUNT(*) AS n FROM items GROUP BY status, gone
`

type CountByStatusGoneRow struct {
	Status string
	Gone   int64
	N      int64
}

func (q *Queries) CountByStatusGone(ctx context.Context) ([]CountByStatusGoneRow, error) {
	rows, err := q.db.QueryContext(ctx, countByStatusGone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountByStatusGoneRow
	for rows.Next() {
		var i CountByStatusGoneRow
		if err := rows.Scan(&i.Status, &i.Gone, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const decideItem = `-- name: DecideItem :execrows
UPDATE items SET status = ?, decided_at = ? WHERE id = ?
`

type DecideItemParams struct {
	Status    string
	DecidedAt int64
	ID        string
}

func (q *Queries) DecideItem(ctx context.Context, arg DecideItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decideItem, arg.Status, arg.DecidedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = ?
`

func (q *Queries) DeleteCollection(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, id)
	return err
}

const deleteConfig = `-- name: DeleteConfig :exec
DELETE FROM configs WHERE id = ?
`

func (q *Queries) DeleteConfig(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteConfig, id)
	return err
}

const deleteNewBySource = `-- name: DeleteNewBySource :exec
DELETE FROM items WHERE source_id = ? AND status = 'new'
`

func (q *Queries) DeleteNewBySource(ctx context.Context, sourceID string) error {
	_, err := q.db.ExecContext(ctx, deleteNewBySource, sourceID)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = ?
`

func (q *Queries) DeleteSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSource, id)
	return err
}

const getCollection = `-- name: GetCollection :one
SELECT id, name, description, source_ids, added_at FROM collections WHERE id = ?
`

func (q *Queries) GetCollection(ctx context.Context, id string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourceIds,
		&i.AddedAt,
	)
	return i, err
}

const getConfig = `-- name: GetConfig :one
SELECT id, name, config_json, added_at FROM configs WHERE id = ?
`

func (q *Queries) GetConfig(ctx context.Context, id string) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfig, id)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ConfigJson,
		&i.AddedAt,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, source_id, label, image_key, url, sample, title, status, gone, added_at, last_seen, decided_at FROM items WHERE id = ?
`

func (q *Queries) GetItem(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Label,
		&i.ImageKey,
		&i.Url,
		&i.Sample,
		&i.Title,
		&i.Status,
		&i.Gone,
		&i.AddedAt,
		&i.LastSeen,
		&i.DecidedAt,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT id, name, description, url, config_file, config_json, added_at, last_poll, last_added, last_error, config_id FROM sources WHERE id = ?
`

func (q *Queries) GetSource(ctx context.Context, id string) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.ConfigFile,
		&i.ConfigJson,
		&i.AddedAt,
		&i.LastPoll,
		&i.LastAdded,
		&i.LastError,
		&i.ConfigID,
	)
	return i, err
}

const getState = `-- name: GetState :one

SELECT last_poll, last_added FROM app_state WHERE id = 1
`

type GetStateRow struct {
	LastPoll  int64
	LastAdded int64
}

// ---------------------------------------------------------------- state
func (q *Queries) GetState(ctx context.Context) (GetStateRow, error) {
	row := q.db.QueryRowContext(ctx, getState)
	var i GetStateRow
	err := row.Scan(&i.LastPoll, &i.LastAdded)
	return i, err
}

const insertCollection = `-- name: InsertCollection :exec
INSERT INTO collections (id, name, description, source_ids, added_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertCollectionParams struct {
	ID          string
	Name        string
	Description string
	SourceIds   string
	AddedAt     int64
}

func (q *Queries) InsertCollection(ctx context.Context, arg InsertCollectionParams) error {
	_, err := q.db.ExecContext(ctx, insertCollection,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SourceIds,
		arg.AddedAt,
	)
	return err
}

const insertConfig = `-- name: InsertConfig :exec
INSERT INTO configs (id, name, config_json, added_at) VALUES (?, ?, ?, ?)
`

type InsertConfigParams struct {
	ID         string
	Name       string
	ConfigJson string
	AddedAt    int64
}

func (q *Queries) InsertConfig(ctx context.Context, arg InsertConfigParams) error {
	_, err := q.db.ExecContext(ctx, insertConfig,
		arg.ID,
		arg.Name,
		arg.ConfigJson,
		arg.AddedAt,
	)
	return err
}

const insertItemIfNew = `-- name: InsertItemIfNew :execrows
INSERT IGNORE INTO items (id, source_id, label, image_key, url, sample, title, status, gone, added_at, last_seen, decided_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertItemIfNewParams struct {
	ID        string
	SourceID  string
	Label     string
	ImageKey  string
	Url       string
	Sample    string
	Title     string
	Status    string
	Gone      int64
	AddedAt   int64
	LastSeen  int64
	DecidedAt int64
}

func (q *Queries) InsertItemIfNew(ctx context.Context, arg InsertItemIfNewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertItemIfNew,
		arg.ID,
		arg.SourceID,
		arg.Label,
		arg.ImageKey,
		arg.Url,
		arg.Sample,
		arg.Title,
		arg.Status,
		arg.Gone,
		arg.AddedAt,
		arg.LastSeen,
		arg.DecidedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertSource = `-- name: InsertSource :exec
INSERT INTO sources (id, name, description, url, config_file, config_json, config_id, added_at, last_poll, last_added, last_error)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSourceParams struct {
	ID          string
	Name        string
	Description string
	Url         string
	ConfigFile  string
	ConfigJson  string
	ConfigID    string
	AddedAt     int64
	LastPoll    int64
	LastAdded   int64
	LastError   string
}

func (q *Queries) InsertSource(ctx context.Context, arg InsertSourceParams) error {
	_, err := q.db.ExecContext(ctx, insertSource,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.ConfigFile,
		arg.ConfigJson,
		arg.ConfigID,
		arg.AddedAt,
		arg.LastPoll,
		arg.LastAdded,
		arg.LastError,
	)
	return err
}

const listCollections = `-- name: ListCollections :many

SELECT id, name, description, source_ids, added_at FROM collections
`

// ------------------------------------------------------------ collections
func (q *Queries) ListCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SourceIds,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigs = `-- name: ListConfigs :many

SELECT id, name, config_json, added_at FROM configs ORDER BY name
`

// ---------------------------------------------------------------- configs
func (q *Queries) ListConfigs(ctx context.Context) ([]Config, error) {
	rows, err := q.db.QueryContext(ctx, listConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ConfigJson,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGood = `-- name: ListGood :many
SELECT id, source_id, label, image_key, url, sample, title, status, gone, added_at, last_seen, decided_at FROM items WHERE status = 'good' ORDER BY decided_at DESC
`

func (q *Queries) ListGood(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listGood)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Label,
			&i.ImageKey,
			&i.Url,
			&i.Sample,
			&i.Title,
			&i.Status,
			&i.Gone,
			&i.AddedAt,
			&i.LastSeen,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewable = `-- name: ListReviewable :many


SELECT id, source_id, label, image_key, url, sample, title, status, gone, added_at, last_seen, decided_at FROM items WHERE status = 'new' AND gone = 0
`

// MySQL / MariaDB queries. Same query names as the SQLite and Postgres files;
// MySQL uses ? placeholders, INSERT IGNORE and ON DUPLICATE KEY UPDATE for the
// upserts (it has no ON CONFLICT).
// ---------------------------------------------------------------- items
func (q *Queries) ListReviewable(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listReviewable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Label,
			&i.ImageKey,
			&i.Url,
			&i.Sample,
			&i.Title,
			&i.Status,
			&i.Gone,
			&i.AddedAt,
			&i.LastSeen,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many

SELECT id, name, description, url, config_file, config_json, added_at, last_poll, last_added, last_error, config_id FROM sources
`

// ---------------------------------------------------------------- sources
func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Url,
			&i.ConfigFile,
			&i.ConfigJson,
			&i.AddedAt,
			&i.LastPoll,
			&i.LastAdded,
			&i.LastError,
			&i.ConfigID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleNew = `-- name: ListStaleNew :many
SELECT id, source_id, label, image_key, url, sample, title, status, gone, added_at, last_seen, decided_at FROM items WHERE gone = 1 AND status = 'new'
`

func (q *Queries) ListStaleNew(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listStaleNew)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Label,
			&i.ImageKey,
			&i.Url,
			&i.Sample,
			&i.Title,
			&i.Status,
			&i.Gone,
			&i.AddedAt,
			&i.LastSeen,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPolled = `-- name: MarkPolled :exec
UPDATE sources SET last_poll = ?, last_added = ?, last_error = '' WHERE id = ?
`

type MarkPolledParams struct {
	LastPoll  int64
	LastAdded int64
	ID        string
}

func (q *Queries) MarkPolled(ctx context.Context, arg MarkPolledParams) error {
	_, err := q.db.ExecContext(ctx, markPolled, arg.LastPoll, arg.LastAdded, arg.ID)
	return err
}

const markSourceGone = `-- name: MarkSourceGone :exec
UPDATE items SET gone = 1 WHERE source_id = ?
`

func (q *Queries) MarkSourceGone(ctx context.Context, sourceID string) error {
	_, err := q.db.ExecContext(ctx, markSourceGone, sourceID)
	return err
}

const purgeStale = `-- name: PurgeStale :execrows
DELETE FROM items WHERE source_id = ? AND gone = 1 AND status <> 'good'
`

func (q *Queries) PurgeStale(ctx context.Context, sourceID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeStale, sourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetItem = `-- name: ResetItem :execrows
UPDATE items SET status = 'new', decided_at = 0 WHERE id = ?
`

func (q *Queries) ResetItem(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setItemStatus = `-- name: SetItemStatus :execrows
UPDATE items SET status = ? WHERE id = ?
`

type SetItemStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) SetItemStatus(ctx context.Context, arg SetItemStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setItemStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSourceError = `-- name: SetSourceError :exec
UPDATE sources SET last_error = ?, last_poll = ? WHERE id = ?
`

type SetSourceErrorParams struct {
	LastError string
	LastPoll  int64
	ID        string
}

func (q *Queries) SetSourceError(ctx context.Context, arg SetSourceErrorParams) error {
	_, err := q.db.ExecContext(ctx, setSourceError, arg.LastError, arg.LastPoll, arg.ID)
	return err
}

const setState = `-- name: SetState :exec
INSERT INTO app_state (id, last_poll, last_added) VALUES (1, ?, ?)
ON DUPLICATE KEY UPDATE last_poll = VALUES(last_poll), last_added = VALUES(last_added)
`

type SetStateParams struct {
	LastPoll  int64
	LastAdded int64
}

func (q *Queries) SetState(ctx context.Context, arg SetStateParams) error {
	_, err := q.db.ExecContext(ctx, setState, arg.LastPoll, arg.LastAdded)
	return err
}

const unstaleItem = `-- name: UnstaleItem :execrows
UPDATE items SET gone = 0, last_seen = ? WHERE id = ?
`

type UnstaleItemParams struct {
	LastSeen int64
	ID       string
}

func (q *Queries) UnstaleItem(ctx context.Context, arg UnstaleItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unstaleItem, arg.LastSeen, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCollection = `-- name: UpdateCollection :exec
UPDATE collections SET name = ?, description = ?, source_ids = ? WHERE id = ?
`

type UpdateCollectionParams struct {
	Name        string
	Description string
	SourceIds   string
	ID          string
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error {
	_, err := q.db.ExecContext(ctx, updateCollection,
		arg.Name,
		arg.Description,
		arg.SourceIds,
		arg.ID,
	)
	return err
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE configs SET name = ?, config_json = ? WHERE id = ?
`

type UpdateConfigParams struct {
	Name       string
	ConfigJson string
	ID         string
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateConfig, arg.Name, arg.ConfigJson, arg.ID)
	return err
}

const updateSource = `-- name: UpdateSource :exec
UPDATE sources SET name = ?, description = ?, url = ?, config_file = ?, config_json = ?, config_id = ?,
    last_poll = ?, last_added = ?, last_error = ? WHERE id = ?
`

type UpdateSourceParams struct {
	Name        string
	Description string
	Url         string
	ConfigFile  string
	ConfigJson  string
	ConfigID    string
	LastPoll    int64
	LastAdded   int64
	LastError   string
	ID          string
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) error {
	_, err := q.db.ExecContext(ctx, updateSource,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.ConfigFile,
		arg.ConfigJson,
		arg.ConfigID,
		arg.LastPoll,
		arg.LastAdded,
		arg.LastError,
		arg.ID,
	)
	return err
}
